spring.application.name=api-gateway
# application-docker.properties
server.port=9000
# use container names for routing
user.service.url=http://user-service:8080
device.service.url=http://device-service:8081
ingestion.service.url=http://ingestion-service:8082
usage.service.url=http://usage-service:8083
alert.service.url=http://alert-service:8084
insight.service.url=http://insight-service:8085

# ===============================
# Management / Actuator
# ===============================
management.health.circuitbreakers.enabled=true
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers,prometheus,gateway
management.metrics.tags.application=${spring.application.name}

# ===============================
# Resilience4j
# ===============================
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
resilience4j.circuitbreaker.configs.default.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.configs.default.slidingWindowSize=8
resilience4j.circuitbreaker.configs.default.failureRateThreshold=20
resilience4j.circuitbreaker.configs.default.minimum-number-of-calls=4
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=5s
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.configs.default.automaticTransitionFromOpenToHalfOpenEnabled=true
server.forward-headers-strategy=framework
# ===============================
# Keycloak
# ===============================
keycloak.auth.jwk-set-uri=http://keycloak:8080/realms/het-security-realm/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/het-security-realm

# ===============================
# Security exclusions
# ===============================
security.excluded.urls=/actuator/**,/swagger-ui.html,/swagger-ui/**,/docs/**,/v3/api-docs/**,/swagger-resources/**,/api-docs/**

# ===============================
# Swagger
# ===============================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

springdoc.swagger-ui.urls[0].name=User Service
springdoc.swagger-ui.urls[0].url=/docs/user-service/v3/api-docs

springdoc.swagger-ui.urls[1].name=Device Service
springdoc.swagger-ui.urls[1].url=/docs/device-service/v3/api-docs

springdoc.swagger-ui.urls[2].name=Ingestion Service
springdoc.swagger-ui.urls[2].url=/docs/ingestion-service/v3/api-docs

springdoc.swagger-ui.urls[3].name=Usage Service
springdoc.swagger-ui.urls[3].url=/docs/usage-service/v3/api-docs

springdoc.swagger-ui.urls[4].name=Alert Service
springdoc.swagger-ui.urls[4].url=/docs/alert-service/v3/api-docs

springdoc.swagger-ui.urls[5].name=Insight Service
springdoc.swagger-ui.urls[5].url=/docs/insight-service/v3/api-docs