spring.application.name=user-service
server.port=8080
server.forward-headers-strategy=framework
springdoc.swagger-ui.disable-swagger-default-url=true
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=when_authorized
management.metrics.tags.application=${spring.application.name}

spring.flyway.enabled=false

spring.datasource.url=jdbc:postgresql://localhost:5433/home_energy_tracker
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect