spring.application.name=complaint-service
server.port=8086
eureka.client.enabled=false
spring.datasource.url=jdbc:postgresql://localhost:5433/home_energy_tracker
spring.datasource.username=postgres
spring.datasource.password=postgres123
aws.access-key=${AWS_ACCESS_KEY}

aws.secret-key=${AWS_SECRET_KEY}
aws.region=eu-north-1
aws.s3.bucket-name=home-energy-tracker-complaints
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
eureka.client.service-url.defaultZone=http://localhost:8761/eureka